;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Peasant",DevComment="")
+GameplayTagList=(Tag="Character.Wolf",DevComment="")
+GameplayTagList=(Tag="Character.Wolf.Alpha",DevComment="")
+GameplayTagList=(Tag="Event",DevComment="")
+GameplayTagList=(Tag="Event.Kill",DevComment="")
+GameplayTagList=(Tag="Event.PickUp",DevComment="")
+GameplayTagList=(Tag="Item.Collectible.Coin",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.WoodenBow",DevComment="")
+GameplayTagList=(Tag="Quest",DevComment="")
+GameplayTagList=(Tag="Quest.BeggarLife",DevComment="")
+GameplayTagList=(Tag="Quest.HuntBegins",DevComment="")
+GameplayTagList=(Tag="Quest.InvalidQuest",DevComment="")
+GameplayTagList=(Tag="Time.Day",DevComment="")
+GameplayTagList=(Tag="Time.Night",DevComment="")

